import { useState } from 'react'
import { Icon } from './ui'
import { CustomerEditForm } from './customers'
import { formatCurrency, formatDateTimeUK, formatDateUK, getCustomerCoordinates, getNextScheduledDate, openGoogleMapsNavigation, type CleanRecord, type Customer } from './crmData'

export function CustomerProfile({ customer, onBack, onSave, onViewMap }: { customer: Customer; onBack: () => void; onSave: (customer: Customer) => void; onViewMap?: (customer: Customer) => void }) {
  const [editing, setEditing] = useState(false)
  const [confirmation, setConfirmation] = useState('')
  const save = (updatedCustomer: Customer) => { onSave(updatedCustomer); setEditing(false); setConfirmation('Changes saved') }
  if (editing) return <><button className="back-button" onClick={() => setEditing(false)}><Icon name="arrow-left" size={19} /> Back to Profile</button><CustomerEditForm customer={customer} onSave={save} onCancel={() => setEditing(false)} /></>
  return <>{confirmation && <p className="save-confirmation" role="status">{confirmation}</p>}<div className="profile-action-row"><button className="back-button" onClick={onBack}><Icon name="arrow-left" size={19} /> Back to Customers</button><button className="edit-customer-button" onClick={() => { setConfirmation(''); setEditing(true) }}>Edit Customer</button></div><CustomerProfileView customer={customer} onViewMap={onViewMap} /></>
}

export function CustomerProfileView({ customer, showPrices = true, onViewMap }: { customer: Customer; showPrices?: boolean; onViewMap?: (customer: Customer) => void }) {
  customer = { ...customer, nextClean: getNextScheduledDate(customer) }
  const locationCoords = getCustomerCoordinates(customer)
  const renderHistoryRecord = (record: CleanRecord, index: number) => {
    const isSkippedOrNoAccess = record.event === 'skipped' || record.event === 'no-access'
    return <div className="history-row" key={`${record.date}-${record.actionedAt || index}`}><span className="history-dot" /><div><strong>{record.event === 'completed' ? 'Window cleaning completed' : record.event === 'no-access' ? 'No Access' : record.event === 'skipped' ? 'Skipped' : 'Job rescheduled'}</strong>{isSkippedOrNoAccess ? <><small>{formatDateTimeUK(record.actionedAt || '', record.date)}</small><small>By {record.actionedBy || 'Unknown user'}</small>{record.reason && <small>Reason: {record.reason}</small>}{showPrices && <small>{formatCurrency(record.price)}{record.worker ? ` · ${record.worker}` : ''}</small>}</> : <small>{formatDateUK(record.date)}{showPrices && <> · {formatCurrency(record.price)}</>}{record.scheduledDate ? ` · New date ${formatDateUK(record.scheduledDate)}` : ''}</small>}</div></div>
  }
  return <><div className="profile-heading"><div className="customer-avatar large">{customer.name.split(' ').map((part) => part[0]).join('')}</div><div><p className="eyebrow">Customer profile</p><h1>{customer.name}</h1><p className="subtitle">Ref {customer.id} <span className={`status-pill ${customer.active ? 'active' : 'inactive'}`}>{customer.active ? 'Active' : 'Inactive'}</span></p></div></div><div className="profile-actions"><button className="secondary-button" onClick={() => onViewMap?.(customer)}><Icon name="pin" size={17} /> View on map</button><button className="secondary-button" onClick={() => openGoogleMapsNavigation(customer)}><Icon name="navigation" size={17} /> Navigate</button></div><div className="profile-grid"><section className="profile-section"><h2>Contact details</h2><dl><div><dt>Telephone</dt><dd><Icon name="phone" size={16} /> {customer.telephone}</dd></div><div><dt>Email</dt><dd><Icon name="mail" size={16} /> {customer.email}</dd></div><div><dt>Full address</dt><dd>{customer.address}<br />{customer.postcode}</dd></div><div><dt>Location</dt><dd>{locationCoords ? <>{locationCoords[0]}, {locationCoords[1]}{!customer.locationVerified && <><br /><small className="location-placeholder-note">Approximate suburb reference point (placeholder) — not confirmed against the exact address</small></>}</> : 'No map location available'}</dd></div></dl></section><section className="profile-section"><h2>Service details</h2><dl><div><dt>Round</dt><dd>{customer.round}</dd></div><div><dt>Service</dt><dd>{customer.service}</dd></div><div><dt>Price</dt><dd>{formatCurrency(customer.price)}</dd></div><div><dt>Frequency</dt><dd>{customer.frequency}</dd></div><div><dt>Preferred day</dt><dd>{customer.preferredDay}</dd></div><div><dt>Payment method</dt><dd>{customer.payment}</dd></div></dl></section><section className="profile-section"><h2>Notes &amp; attachments</h2><p className="profile-notes">{customer.notes}</p><button className="attachment-row"><Icon name="paperclip" size={17} /><span>Property notes.pdf</span><Icon name="chevron" size={16} /></button></section><section className="profile-section"><h2>Cleaning history</h2><div className="clean-dates"><div><span>Last clean</span><strong>{formatDateUK(customer.lastClean)}</strong></div><div><span>Next clean</span><strong>{formatDateUK(customer.nextClean)}</strong></div></div>{customer.cleanHistory.length ? customer.cleanHistory.slice().reverse().map(renderHistoryRecord) : <div className="history-row"><span className="history-dot" /><div><strong>No completed cleans recorded</strong><small>History will appear after a job is completed.</small></div></div>}<button className="history-button">View customer/job history <Icon name="chevron" size={16} /></button></section></div></>
}
