import { Icon, type IconName } from './ui'
import { WorkloadPlanner } from './schedule'
import type { Customer } from './crmData'

const summaryCards = [
  { label: 'Active Customers', value: '1,021', detail: '+4.8% this month', icon: 'users' as IconName, tone: 'blue' }, { label: 'Round Value', value: '£15,848', detail: 'Monthly recurring', icon: 'pound' as IconName, tone: 'teal' }, { label: "Today's Jobs", value: '28', detail: '6 still to complete', icon: 'calendar' as IconName, tone: 'amber' }, { label: "Today's Scheduled Value", value: '£1,264', detail: 'Across 4 teams', icon: 'pound' as IconName, tone: 'blue' }, { label: 'Jobs Completed', value: '19', detail: '68% of today', icon: 'check' as IconName, tone: 'green' }, { label: 'Value Completed', value: '£842', detail: '£422 remaining', icon: 'check' as IconName, tone: 'green' },
]
const attentionCards = [
  { label: 'Customer Issues', value: '3', note: 'Need your attention', icon: 'alert' as IconName, tone: 'coral' }, { label: 'No Access', value: '2', note: 'Jobs to reschedule', icon: 'door' as IconName, tone: 'amber' }, { label: 'New Leads', value: '7', note: 'Since yesterday', icon: 'user-plus' as IconName, tone: 'teal' }, { label: 'Messages', value: '5', note: 'Unread messages', icon: 'message' as IconName, tone: 'blue' },
]
const actions = [
  { label: 'Customers', icon: 'users' as IconName, tone: 'blue' }, { label: 'Rounds', icon: 'rounds' as IconName, tone: 'teal' }, { label: "Today's Work", icon: 'briefcase' as IconName, tone: 'amber' }, { label: 'Map', icon: 'map' as IconName, tone: 'coral' }, { label: 'Workers', icon: 'users' as IconName, tone: 'violet' }, { label: 'Messages', icon: 'message' as IconName, tone: 'blue' }, { label: 'Leads', icon: 'user-plus' as IconName, tone: 'teal' }, { label: 'AI Assistant', icon: 'sparkle' as IconName, tone: 'violet' },
]

export function Home({ customerRecords, onCustomers, onRounds, onWork, onMap }: { customerRecords: Customer[]; onCustomers: () => void; onRounds: () => void; onWork: () => void; onMap: () => void }) {
  return <><div className="welcome-row"><div><p className="eyebrow">Saturday, 05 September 2026</p><h1>Good morning, Gavin</h1><p className="subtitle">Here&apos;s what&apos;s happening with your business today.</p></div><button className="date-button"><Icon name="calendar" size={18} /> Today <Icon name="chevron" size={16} /></button></div><section aria-labelledby="overview-title"><div className="section-heading"><h2 id="overview-title">Overview</h2><span>Updated just now</span></div><div className="summary-grid">{summaryCards.map((card) => <article className="summary-card" key={card.label}><div className={`metric-icon ${card.tone}`}><Icon name={card.icon} size={21} /></div><div><p>{card.label}</p><strong>{card.value}</strong><small>{card.detail}</small></div></article>)}</div></section><section aria-labelledby="attention-title"><div className="section-heading"><h2 id="attention-title">Attention Needed</h2><button className="text-button">View all <Icon name="chevron" size={16} /></button></div><div className="attention-grid">{attentionCards.map((card) => <button className="attention-card" key={card.label}><div className={`attention-icon ${card.tone}`}><Icon name={card.icon} size={21} /></div><span><b>{card.label}</b><small>{card.note}</small></span><strong>{card.value}</strong><Icon name="chevron" size={17} /></button>)}</div></section><WorkloadPlanner customerRecords={customerRecords} /><section aria-labelledby="quick-title"><div className="section-heading"><h2 id="quick-title">Quick access</h2></div><div className="action-grid">{actions.map((action) => <button className="action-card" key={action.label} onClick={action.label === 'Customers' ? onCustomers : action.label === 'Rounds' ? onRounds : action.label === "Today's Work" ? onWork : action.label === 'Map' ? onMap : undefined}><span className={`action-icon ${action.tone}`}><Icon name={action.icon} size={22} /></span><span>{action.label}</span><Icon name="chevron" size={17} /></button>)}</div></section></>
}
