import { useState } from 'react'
import { DatePickerField } from './rounds'
import { Icon } from './ui'
import { addDays, canSeeJobPrices, formatCurrency, formatDayShort, formatWeekLabel, getRouteOrder, getScheduledJobsForDate, startOfWeekMonday, todayISO, type CrmUser, type Customer, type ScheduledJob } from './crmData'

export function ScheduledJobsPanel({ customerRecords, date, title, user, showPrices = true, onReschedule, onOpenCustomer }: { customerRecords: Customer[]; date: string; title: string; user?: CrmUser; showPrices?: boolean; onReschedule?: (customerId: string, oldDate: string, newDate: string) => void; onOpenCustomer?: (customer: Customer) => void }) {
  const jobs = getScheduledJobsForDate(customerRecords, date, user)
  const routeOrder = getRouteOrder(customerRecords)
  const [rescheduling, setRescheduling] = useState<ScheduledJob | null>(null)
  const [rescheduleDate, setRescheduleDate] = useState('')
  const openReschedule = (job: ScheduledJob) => { setRescheduling(job); setRescheduleDate(job.occurrence.date) }
  const confirmReschedule = () => { if (!rescheduling || !rescheduleDate || rescheduleDate === rescheduling.occurrence.date) return; onReschedule?.(rescheduling.customer.id, rescheduling.occurrence.date, rescheduleDate); setRescheduling(null) }
  return <div className="schedule-jobs-panel"><div className="section-heading"><h3>{title}</h3><span>{jobs.length} scheduled</span></div>{jobs.length ? <div className="today-job-list">{jobs.map(({ customer, occurrence }, index) => <article className={`today-job ${onOpenCustomer ? 'clickable-job' : ''}`} key={occurrence.id} onClick={() => onOpenCustomer?.(customer)} role={onOpenCustomer ? 'button' : undefined} tabIndex={onOpenCustomer ? 0 : undefined} onKeyDown={onOpenCustomer ? (event) => { if (event.key === 'Enter' || event.key === ' ') { event.preventDefault(); onOpenCustomer(customer) } } : undefined}><div className="today-job-top"><span className="route-number">{routeOrder.get(customer.id) ?? customer.routePosition ?? index + 1}</span><strong>{customer.name}</strong><span className="job-status scheduled-status">Scheduled</span></div><div className="today-job-details"><span>{customer.address}, {customer.postcode}</span></div><div className="today-job-assignment"><span>{occurrence.round}</span><span aria-hidden="true">·</span><span>{occurrence.worker || 'Unassigned'}</span></div><div className="today-job-pricing">{showPrices && <><span>{formatCurrency(occurrence.price)}</span><span aria-hidden="true">·</span></>}<span>{customer.frequency}</span></div>{onReschedule && <div className="today-job-actions" onClick={(event) => event.stopPropagation()}><button type="button" className="secondary-button" onClick={() => openReschedule({ customer, occurrence })}>Reschedule</button></div>}</article>)}</div> : <div className="empty-state"><Icon name="calendar" size={24} /><strong>No scheduled jobs</strong><span>There are no active scheduled jobs for this day.</span></div>}{rescheduling && <div className="job-confirmation-backdrop"><div className="job-confirmation" role="dialog" aria-modal="true" aria-labelledby="future-reschedule-title"><h2 id="future-reschedule-title">Reschedule visit</h2><p>Moves only <strong>{rescheduling.customer.name}</strong>&apos;s visit on <strong>{formatDayShort(rescheduling.occurrence.date)}</strong> to a new date. The customer&apos;s normal frequency and the round&apos;s cycle dates are unchanged.</p><DatePickerField label="New date" value={rescheduleDate} min={todayISO()} onChange={setRescheduleDate} required /><div><button className="secondary-button" onClick={() => setRescheduling(null)}>Cancel</button><button className="primary-button" disabled={!rescheduleDate || rescheduleDate === rescheduling.occurrence.date} onClick={confirmReschedule}>Confirm reschedule</button></div></div></div>}</div>
}

export function ComingUpSection({ customerRecords, user, onReschedule, onOpenCustomer }: { customerRecords: Customer[]; user?: CrmUser; onReschedule?: (customerId: string, oldDate: string, newDate: string) => void; onOpenCustomer?: (customer: Customer) => void }) {
  const [selectedDate, setSelectedDate] = useState<string | null>(null)
  const dates = [1, 2, 3].map((days) => addDays(todayISO(), days))
  const showPrices = !user || canSeeJobPrices(user)
  return <section className="coming-up-section" aria-labelledby="coming-up-title"><div className="section-heading"><div><h2 id="coming-up-title">Coming up</h2><span className="section-supporting-text">Next 3 days</span></div></div><div className="coming-up-list">{dates.map((date) => { const jobs = getScheduledJobsForDate(customerRecords, date, user); return <button className={`coming-up-card ${selectedDate === date ? 'selected' : ''}`} key={date} onClick={() => setSelectedDate(selectedDate === date ? null : date)}><strong>{formatDayShort(date)}</strong><span>{jobs.length} {jobs.length === 1 ? 'job' : 'jobs'}</span>{showPrices && <b>{formatCurrency(jobs.reduce((total, job) => total + job.occurrence.price, 0))}</b>}</button> })}</div>{selectedDate && <ScheduledJobsPanel customerRecords={customerRecords} date={selectedDate} title={`Scheduled jobs · ${formatDayShort(selectedDate)}`} user={user} showPrices={showPrices} onReschedule={onReschedule} onOpenCustomer={onOpenCustomer} />}</section>
}

export function WorkloadPlanner({ customerRecords }: { customerRecords: Customer[] }) {
  const [weekOffset, setWeekOffset] = useState(0)
  const [selectedDate, setSelectedDate] = useState<string | null>(null)
  const weekStart = addDays(startOfWeekMonday(todayISO()), weekOffset * 7)
  const dates = Array.from({ length: 7 }, (_, index) => addDays(weekStart, index))
  const daySummaries = dates.map((date) => ({ date, jobs: getScheduledJobsForDate(customerRecords, date) }))
  const busiestDay = Math.max(...daySummaries.map((day) => day.jobs.length), 1)
  return <section className="workload-planner" aria-labelledby="workload-planner-title"><div className="section-heading planner-heading"><div><h2 id="workload-planner-title">Workload planner</h2><span className="section-supporting-text">Scheduled jobs by day</span></div><div className="planner-controls"><button className="text-button" onClick={() => { setWeekOffset((offset) => offset - 1); setSelectedDate(null) }}>&lt; Previous week</button><strong>{weekOffset === 0 ? 'This week' : formatWeekLabel(weekStart)}</strong><button className="text-button" onClick={() => { setWeekOffset((offset) => offset + 1); setSelectedDate(null) }}>Next week &gt;</button></div></div><div className="planner-week-label">{formatWeekLabel(weekStart)}</div><p className="planner-scroll-hint" aria-hidden="true">Swipe to see the full week &rarr;</p><div className="planner-grid-scroll"><div className="planner-grid">{daySummaries.map(({ date, jobs }) => { const value = jobs.reduce((total, job) => total + job.occurrence.price, 0); return <button className={`planner-day ${selectedDate === date ? 'selected' : ''}`} key={date} onClick={() => setSelectedDate(selectedDate === date ? null : date)}><span>{formatDayShort(date)}</span><strong>{jobs.length}</strong><small>{jobs.length === 1 ? 'scheduled job' : 'scheduled jobs'}</small><i><b style={{ width: `${(jobs.length / busiestDay) * 100}%` }} /></i><em>{formatCurrency(value)}</em></button> })}</div></div>{selectedDate && <ScheduledJobsPanel customerRecords={customerRecords} date={selectedDate} title={`Scheduled jobs · ${formatDayShort(selectedDate)}`} />}</section>
}
